// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtJnZRs90AJl-NLr3Moyeuzdw3K6Tpo2M',
    appId: '1:495111595993:web:0a02ab0ef20f63ff89dbc8',
    messagingSenderId: '495111595993',
    projectId: 'finance-5b1b4',
    authDomain: 'finance-5b1b4.firebaseapp.com',
    storageBucket: 'finance-5b1b4.firebasestorage.app',
    measurementId: 'G-RZ8HNLNBE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHsDDgbcZrCGQCPK_CWfR_TLAOrEjnspU',
    appId: '1:495111595993:android:c99abd8e3a7e1c7189dbc8',
    messagingSenderId: '495111595993',
    projectId: 'finance-5b1b4',
    storageBucket: 'finance-5b1b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE6X8ekU9Lb3a-85RduVodSL9iTF-O9lo',
    appId: '1:495111595993:ios:bf90caf712c80d8089dbc8',
    messagingSenderId: '495111595993',
    projectId: 'finance-5b1b4',
    storageBucket: 'finance-5b1b4.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE6X8ekU9Lb3a-85RduVodSL9iTF-O9lo',
    appId: '1:495111595993:ios:bf90caf712c80d8089dbc8',
    messagingSenderId: '495111595993',
    projectId: 'finance-5b1b4',
    storageBucket: 'finance-5b1b4.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtJnZRs90AJl-NLr3Moyeuzdw3K6Tpo2M',
    appId: '1:495111595993:web:a70081494b79609e89dbc8',
    messagingSenderId: '495111595993',
    projectId: 'finance-5b1b4',
    authDomain: 'finance-5b1b4.firebaseapp.com',
    storageBucket: 'finance-5b1b4.firebasestorage.app',
    measurementId: 'G-RK8Y4V0XMM',
  );
}
